<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MyFinanceWeb.Domain/MyFinanceWeb.Domain.csproj" />
    <ProjectReference Include="../MyFinanceWeb.Infra/MyFinanceWeb.Infra.csproj" />
  </ItemGroup>

</Project>
